apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    namespace: pprometheus
    server: 'https://kubernetes.default.svc'
  source:
    path: packages/prometheus
    repoURL: 'https://github.com/crevillo/argocd.git'
    targetRevision: HEAD
    helm:
      version: v3
      valueFiles:
        - ../../values/prometheus.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true