apiVersion: v2
name: postgres
description: Postgres 

type: application

version: 10.2.2

appVersion: 11.10.0

dependencies:
- name: postgres
  repository: https://charts.bitnami.com/bitnami
  version: 10.2.2