apiVersion: v2
name: postgres
description: Postgres 

type: application

version: 11.10.0

appVersion: 10.2.2

dependencies:
- name: postgres
  repository: https://groundhog2k.github.io/helm-charts/
  version: 11.10.0